packages:
  - apps/*
  - packages/*
  - docker/*

ignoredBuiltDependencies:
  - bcrypt

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
